### ISSUE TITLE
Corrupt header on .REC file.

### ISSUE THREAD

**Issue by Gavinfinlaysmith** [holophantstudios/VoxonXBlender#2]
I recordered a .REC file, but when played back it says the header is corrupt.

See attached .blend and .rec

[dolphin.002.zip](https://github.com/holophantstudios/VoxonXBlender/files/11711807/dolphin.002.zip)

**Comment by Gavinfinlaysmith** [comment]
I think I found the issue. I disabled the spline ( the path that the dolphin was following ), and it then worked.  I don't think the .rec likes splines maybe.

**Comment by holophantstudios** [comment]
The render actually failed, which is why voxieplay was unable to play it.  I fixed the issue (it was a stupid indentation mistake) and will push the change to master soon.  Going forward I will try to make it more clear when a recording fails to prevent confusion

**Comment by holophantstudios** [comment]
Confirmed that fix worked and has been pushed to master.  You can update your add-on to the master branch to fix it on your local machine.
